# Databricks SQL Warehouse
DATABRICKS_HOST = "adb-XXXXXXXXX.13.azuredatabricks.net"
DATABRICKS_HTTP_PATH = "/sql/1.0/warehouses/XXXXXXXXX"
DATABRICKS_TOKEN = "chave-Databricks"

# Google Gemini
GEMINI_API_KEY = "sua-chave-google-ai-studio"
